### ISSUE TITLE
Very similar build

### ISSUE THREAD

**Issue by verdazil** [ernestkck/Hackintosh-Gigabyte-Z690-Aorus-Ultra-12600K-RX6900-XT#1]
Hi
My build: Gigabyte Z690 AORUS ULTRA (rev. 1.0); Intel® Core™ i7-12700KF; Kingston FURY, KF560C32RSK2-32, DDR5-6000 CL32-38-38 @1.35V; AMD Radeon RX 6600, macOS Sonoma 14.4 (23E214)

I confirm the following:
doesn't work sleep, problems with reboot and shutdown. When rebooting, it sometimes freezes, forcing me to shut down the computer completely. Sometimes it is enough to wait 30-40 seconds and the reboot occurs. When turning off the computer, sometimes I need to wait 30-40 seconds or hold down the Power button.
ACPI patches or additional SSDT-s do not solve the problem, I tested everything that Dortania offers...

**Comment by ernestkck** [comment]
Hi I haven't had much time testing sleep, but shutting down and rebooting seem to be working for me. I've uploaded my EFI folder so maybe that can help.

**Comment by verdazil** [comment]
Hi,
Thank you, the problem with PC shutting down and restarting was resolved using the following setting:

<dict>
	<key>DeviceProperties</key>

	<dict>
		<key>Add</key>

		<dict>
			<key>PciRoot(0x0)/Pci(0x17,0x0)</key>

			<dict>
				<key>compatible</key>
				<string>pci8086,a352</string>
			</dict>

		</dict>
	</dict>
</dict>
